### ISSUE TITLE
php easyswoole migrate run

### ISSUE THREAD

**Issue by FairyTtail** [Joyboo/Joyboo-admin-easyswoole#5]
命令执行后连接不上mysql
Fatal error: Uncaught EasySwoole\Mysqli\Exception\Exception: SQLSTATE[HY000] [2002] Connection reset by peer or Transport endpoint is not connected in /mnt/d/wamp64/www/Joyboo-admin-easyswoole/vendor/easyswoole/mysqli/src/Client.php:69
Stack trace:
#0 /mnt/d/wamp64/www/Joyboo-admin-easyswoole/vendor/easyswoole/db-migrate/src/MigrateManager.php(58): EasySwoole\Mysqli\Client->execBuilder()
#1 /mnt/d/wamp64/www/Joyboo-admin-easyswoole/vendor/easyswoole/db-migrate/src/MigrateCommand.php(136): EasySwoole\DatabaseMigrate\MigrateManager->query('SHOW TABLES LIK...')
#2 /mnt/d/wamp64/www/Joyboo-admin-easyswoole/vendor/easyswoole/db-migrate/src/MigrateCommand.php(100): EasySwoole\DatabaseMigrate\MigrateCommand->checkDefaultMigrateTable()
#3 [internal function]: EasySwoole\DatabaseMigrate\MigrateCommand->EasySwoole\DatabaseMigrate\{closure}()
#4 {main}
  thrown in /mnt/d/wamp64/www/Joyboo-admin-easyswoole/vendor/easyswoole/mysqli/src/Client.php on line 69

**Comment by Joyboo** [comment]
请检查：
- 是否创建 `vben_admin` 数据库
- 数据库配置是否正确
